export {default as Hero} from "./hero.jsx"
export {default as Bar} from "./bar.jsx"
export {default as About} from "./about.jsx"
export {default as Tech} from "./tech.jsx"
export {default as Projects} from "./projects.jsx"
export {default as Contact } from "./contact.jsx"
